### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by JustAPerson** [bovard/archon#5]
Hi, this happens partially through running a match using the 0.2.2 client

```
[jason@metroid battlecode]$ archon match -lxm src/teamA src/teamB
Running 108 matches on 54 maps between 2 teams
6147.xml [teamA/teamB] teamB 1863
6147.xml [teamB/teamA] teamB 1512
arena.xml [teamA/teamB] teamA 1843
arena.xml [teamB/teamA] teamB 2819
backbencher.xml [teamA/teamB] teamB 1972
backbencher.xml [teamB/teamA] teamB 1961
barred.xml [teamA/teamB] teamB 1742
barred.xml [teamB/teamA] teamB 1433
barricade.xml [teamA/teamB] teamA 1510
barricade.xml [teamB/teamA] teamB 1624
boxy.xml [teamA/teamB] teamA 1811
boxy.xml [teamB/teamA] teamB 2999

/usr/local/lib/node_modules/archon/lib/game.js:39
                round = parseInt(split[2].split(' ')[1]);
                                          ^
TypeError: Cannot call method 'split' of undefined
    at Socket.<anonymous> (/usr/local/lib/node_modules/archon/lib/game.js:39:43)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at Pipe.onread (net.js:526:21)
```

**Comment by bovard** [comment]
@JustAPerson archon doesn't like boxy_armageddon if you remove it from the list you should be good
